name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
#    container: ocaml/opam2
    
    steps:
    - name: Install packages
      run: sudo apt-get install build-essential cmake vim doxygen libfreetype6 libfreetype6-dev libtbb-dev libfreeimage3 libfreeimage-dev
    - uses: actions/checkout@v2
    - name: test
      run: uname -a
#    - name: test
#      run: pwd
#    - name: My first step
#      uses: docker://alpine:3.8
#    - name: test
#      run: uname -a
#    - name: test
#      run: pwd
