name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:19.10
    
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: uname -a
    - name: test
      run: pwd
    - name: My first step
      uses: docker://alpine:3.8
    - name: test
      run: uname -a
    - name: test
      run: pwd
