name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
#    container: ocaml/opam2
    
    steps:
    - name: Check version
      run: lsb_release -a
    - name: Install packages
      run: sudo apt-get install build-essential cmake vim doxygen libfreetype6 libfreetype6-dev libtbb-dev libfreeimage3 libfreeimage-dev libxmu-dev libxi-dev
    - name: Install de la suite
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tcl8.6 tk8.6 tcl8.6-dev tk8.6-dev tcl8.6-doc tk8.6-doc
    - name: Encore la suite
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libvtk6.3 libvtk6-dev
    - uses: actions/checkout@v2
    - name: Position
      run: pwd && ls -lisa 
#    - name: SetUp 
    - run: |
       cd opencascade-7.2.0
       mkdir build
       cd build 
       cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug .. 
       make -j2 install
#    - uses: actions/checkout@v2
#    - name: test
#      run: uname -a
#    - name: test
#      run: pwd
#    - name: My first step
#      uses: docker://alpine:3.8
#    - name: test
#      run: uname -a
#    - name: test
#      run: pwd
